version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./themes:/app/themes
    environment:
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=sqlite:///steam_theme_studio.db
      - CORS_ORIGINS=["http://localhost:3000"]
    restart: unless-stopped 